# Generated by Django 5.1.5 on 2025-07-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
