# Generated by Django 5.1.5 on 2025-07-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_attendee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='phone',
        ),
        migrations.AddField(
            model_name='attendee',
            name='category',
            field=models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10),
        ),
        migrations.AddField(
            model_name='attendee',
            name='detail',
            field=models.CharField(blank=True, help_text='For adults: select title (Mr, Ms, etc). For children: select age group.', max_length=10, null=True),
        ),
    ]
