services:
  - type: web
    name: event-manager
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn event_manager.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: event_manager.settings
      - key: PYTHON_VERSION
        value: 3.10
